movies/2013/star-trek-into-darkness.json
movies/2016/star-trek-beyond.json

All information taken from imdb: [Star Trek Beyond](http://www.imdb.com/title/tt2660888/) and [Star Trek Into Darkness](http://www.imdb.com/title/tt1408101/).
I wasn't sure how many actors you wanted to list, let me know if you want more or less 😃

Adds Star Trek Into Darkness and Star Trek Beyond

---

movies/2000/x-men.json
movies/2003/x-men-2.json
movies/2006/x-men-the-last-stand.json
movies/2009/x-men-origins-wolverine.json
movies/2011/x-men-first-class.json
movies/2013/the-wolverine.json
movies/2014/x-men-days-of-future-past.json
movies/2016/x-men-apocalypse.json

Resolves jsonmc/jsonmc/issues/16

Add X-Men movies

---

movies/2007/fantastic-four-rise-of-the-silver-surfer.json
movies/2008/the-incredible-hulk.json
movies/2014/guardians-of-the-galaxy.json
movies/2015/ant-man.json

Added more Marvel Movies

---

.gitignore
.travis.yml
package.json
test.js

Travis tests using jshint

---

movies/2001/the-lord-of-the-rings-fellowship-of-the-ring.json
movies/2002/the-lord-of-the-rings-the-two-towers.json
movies/2003/the-lord-of-the-rings-the-return-of-the-king.json
movies/2012/the-hobbit-an-unexpected-journey.json
movies/2013/the-hobbit-the-desolation-of-smaug.json
movies/2014/the-hobbit-the-battle-of-the-five-armies.json

Added Lord of the Rings and Hobbit series

---

movies/1984/the-terminator.json
movies/1991/terminator-2-judgement-day.json
movies/2003/terminator-3-rise-of-the-machines.json
movies/2009/terminator-salvation.json
movies/2015/terminator-genisys.json

fixed syntax error in terminator 2

Adding terminator movies (fixed)

---

movies/2001/harry-potter-and-the-sorcerers-stone.json
movies/2002/harry-potter-and-the-chamber-of-secrets.json
movies/2004/harry-potter-and-the-prisoner-of-azkaban.json
movies/2005/harry-potter-and-the-goblet-of-fire.json
movies/2007/harry-potter-and-the-order-of-the-phoenix.json
movies/2009/harry-potter-and-the-half-blood-prince.json
movies/2010/harry-potter-and-the-deathly-hallows-part-1.json
movies/2011/harry-potter-and-the-deathly-hallows-part-2.json

This should solve #42. Description part is referenced from [WarnerBros](http://www.warnerbros.com/harry-potter-and-deathly-hallows-part-2).

Add Harry Potter movies 

---

movies/1978/superman.json
movies/1981/superman-2.json
movies/1983/superman-3.json
movies/1987/superman-4.json
movies/2006/superman-returns.json
movies/2013/man-of-steel.json
movies/2016/batman-v-superman.json

Add superman movies

---

movies/1989/the-punisher.json
movies/2004/the-punisher.json
movies/2008/punisher-war-zone.json

Added The Punisher (1989), The Punisher (2004), and Punisher: War Zone (2008) to Marvel Movies issue: https://github.com/jsonmc/jsonmc/issues/6

Add The Punisher movies

---

movies/2016/La La Land.txt

Adding La La Land to movies

---

actors/ben-affleck.json

Adds Ben Affleck

---

actors/will-smith.json

Adds actor: Will Smith

---

movies/1982/blade-runner.json
movies/2017/blade-runner-2049.json

Adds films; Blade Runner, Blade Runner 2049

---

movies/2017/ghost-in-the-shell

Create ghost-in-the-shell HacktoberFest

---

movies/2017/ghost-in-the-shell.json

I have added a .json for ghost in the shell as a part of contribution in hacktoberfest 2017

added ghost in the shell (2017) for Hacktoberfest

---

directors/stephen-spielberg.json

Add directors directory with Stephen Spielberg. Closes #98.

Add directors and include Stephen Spielberg

---

actors/donald-glover.json

Add Donald Glover to actors

---

actors/natalie-portman.json

Fixes https://github.com/jsonmc/jsonmc/issues/84

added natalie portman data

---

actors/bruce-willis.json
actors/haley-joel-osment.json
actors/toni-collete.json
movies/1999/the-sixth-sense.json

- The Sixth Sense (1999)
- Bruce Willis
- Haley Joel Osment
- Toni Collette

added The Sixth Sense (1999) and some actors

---

movies/2017/guardians-of-the-galaxy-2.json
movies/2017/spiderman-homecoming.json
movies/2017/thor-ragnarok.json

Part of #6 
Added all 3 2017 marvel movies.

Added 2017 marvel movies

---

movies/2015/capitao-falcao.json

Added a portuguese movie for a change.

Added Capitao Falcao

---

movies/1997/starship-troopers.json

Add Starship Troopers to movies.

Add Starship Troopers to Movies

---

movies/1962/dr-no.json
movies/1963/from-russia-with-love.json
movies/1964/goldfinger.json
movies/1965/thunderball.json
movies/1967/you-only-live-twice.json
movies/1971/diamons-are-forever.json
movies/1983/never-say-never-again.json

Added James Bond (Sean Connery) films

---

movies/2017/annabelle.json

Added Annabelle: Creations

---

movies/2017/war-of-the-planet-of-the-apes.json

Added War Of The Planet Of The Apes

---

movies/2009/the-orphan.json

Added Orphan

---

movies/2016/the-conjuring-2.json

Added conjuring

---

movies/2016/underworld-blood-wars.json

fixed #159
created underworld-blood-wars.json

created underworld-blood-wars.json

---

movies/2013/percy-jackson-sea-of-monsters.json
movies/2014/big-hero-6.json
movies/2016/underworld-blood-wars.json

Added movies for issues #157 , #158 and #159 using really complex software.

Added movies for issues #157-9

---

actors/ed-speleers.json
actors/jeremy-irons.json
actors/john-malkovich.json
actors/robert-carlyle.json
actors/sienna-guillory.json
movies/2006/eragon.json

For the theme of Hacktoberfest, I decided to add the movie that destroyed a series that could've been great.

Add eragon movie and main actors

---

movies/2018/rampage.json

- Added 2018 folder
- Added Rampage #201

Added Rampage (Fixes #201)

---

movies/2018/aquaman.json

added aquaman movie

---

movies/1986/top-gun.json

This PR fixes [#245](https://github.com/jsonmc/jsonmc/issues/245)
Cheers!

Adds Movie: Top Gun

---

movies/1979/alien.json
movies/1979/life-of-brian.json

The movie alien is added as requested by #247

Added Alien movie

---

movies/2000/the-replacements.json

Add movie the replacements

---

actors/benedict-cumberbatch.json
movies/2010/the-book-of-eli.json
movies/2018/rampage.json

- Added *The Book of Eli* #215
- Added the Benedict Cumberbatch
Fixes #215

Added The Book of Eli #215

---

movies/1986/labyrinth.json

Fixes https://github.com/jsonmc/jsonmc/issues/216

Fix #216 Added 1986 folder and Labyrinth movie

---

movies/2009/watchmen.json

Added Watchmen #198

---

tests/tests.js

Add actor tests (#212)

---

movies/1962/to-kill-a-mockingbird.json

Adding entry for the film To Kill a Mockingbird

Add To Kill a Mockingbird

---

movies/2001/memento.json

Add Memento movie
data taken from wikipedia: https://en.wikipedia.org/wiki/Memento_(film)

Add Movie Memento

---

actors/benedict-cumberbatch.json

Add Benedict Cumberbatch

---

movies/2018/crazy-rich-asians.json

crazy-rich-asians.json

---

directors/stanley-kubrick.json

Added director Stanley Kubrick

---

actors/steve-carell.json

Add steve carell

---

actors/jason-momoa.json

Added actor: Jason Momoa

---

actors/macaulay-culkin.json

Macaulay Culkin

---

movies/2018/searching.json

Added movie info for Searching

---

tests/tests.js

Fixes #295 
The test now checks to see if all JSON filenames are lowercase

Improve test

---

actors/jennifer-connelly.json

Add Jennifer Connelly

---

actors/owen-wilson.json

Added actor Owen Wilson

---

actors/jackie-chan.json

Fixes #329 
Added jackie Chan, please let me know if this is alright formatting.

adding actor Jackie Chan

---

movies/2014/lucy.json

As per user story, .json file for movie Lucy was added.
Fixes #333

movie Lucy added

---

actors/james-mcavoy.json
actors/paul-rudd.json

Added Paul Rudd

---

actors/jonah-hill.json

Added Jonah Hill

---

actors/tye-sheridan.json

Added Actor Tye Sheridan

---

actors/lana-condor.json

Added Actress Lana Condor

---

movies/2011/the-rum-diary.json

Added The Rum diary

---

actors/lucas-till.json

Added Actor Lucas Till

---

actors/jaden-smith.json

added jaden smith

---

movies/1994/little-giants.json

Add Movie Little Giants

---

actors/josh-helman.json

Added Actor Josh Helman

---

actors/keanu-reeves.json
actors/skeet-ulrich.json

Create Keanu Reeves

---

movies/2016/kingsglaive-final-fantasy-xv.json

Add Kingsglaive Final Fantasy XV movie

---

actors/evangeline-lilly.json

Added Evangeline Lilly

---

actors/christoph-waltz.json
actors/jaden-smith.json

Added Christoph waltz

---

movies/2010/the-tourist.json

Added The Tourist

---

actors/james-mcavoy.json

Added James McAvoy

---

actors/daniel-radcliffe.json

Added Daniel Radcliffe to actors

---

tests/tests.js

Update tests: All movies must have either 'future:true' or 'runtime:<number>'.

---

movies/1972/the-godfather.json

Added movie : The Godfather

---

movies/1990/the-godfather-part-iii.json

Added The Godfather III movie.

---

actors/sean-penn.json

Add Sean Penn

---

actors/anya-taylor-joy.json

Added Anya Taylor-Joy

---

movies/2016/warcraft.json

Added Warcraft movie

---

movies/2015/mortdecai.json

Added Mortdecai

---

actors/burt-reynolds.json

Add Burt Reynolds

---

actors/patrick-dempsey.json

Add Patrick Dempsey

---

actors/keanu-reeves.json
actors/skeet-ulrich.json

Hopefully I did it right this time!
Fixes #419

Create Skeet Ulrich

---

actors/anne-hathaway.json
actors/jonah-hill.json

Added Anne hathaway

---

movies/2004/secret-window.json

Added Secret Window

---

actors/anatole-taubman.json

Add Anatole Taubman

---

actors/jason-mewes.json

Add Jason Mewes

---

directors/woody-allen.json

Add Woody Allen

---

actors/jennifer-garner.json

add Jennifer Garner

---

actors/stephen-amell.json

Add Stephen Amell

---

actors/amber-heard.json
actors/amy-adams.json
actors/gal-gadot.json
actors/tom-hardy.json

Add Actress : Amy Adams

---

actors/aamir-khan.json
actors/amber-heard.json
actors/amy-adams.json
actors/gal-gadot.json
actors/tom-hardy.json

Add Actor : Aamir Khan

---

actors/nick-offerman.json

Add Actor: Nick Offerman

---

directors/david-fincher.json

Add Director: David Fincher

---

directors/francis-ford-coppola.json

Add Director: Francis Ford Coppola

---

actors/piper-perabo.json

Add Actress: Piper Perabo

---

directors/park-chan-wook.json

Add Director: Park Chan-wook

---

actors/mads-mikkelsen.json

Add Actor: Mads Mikkelsen

---

actors/martin-freeman.json

Add Actor: Martin Freeman

---

actors/hugh-jackman.json

Added Actor Hugh Jackman

---

actors/jennifer-lawrence.json

Jennifer Lawrence description.

jennifer-lawrence.json

---

actors/will-ferrell.json

https://en.wikipedia.org/wiki/Will_Ferrell

Add actor "Will Ferrell"

---

movies/2003/the-room.json

Hi; I'd like to add the movie "The Room" to the database; thank you 😄

Add "The Room"

---

actors/akshay-kumar.json
actors/ashton-kutcher.json
actors/nawazuddin-siddiqui.json
directors/damien-chazelle.json
directors/imtiaz-ali.json
directors/rajkumar-hirani.json

add actors and directors in json file

add actors and directors in json file

---

movies/2017/baby-driver.json

Added movie: Baby Driver

---

actors/nicolas-cage.json

Added nick cage info

---

movies/2018/the-house-with-a-clock-in-its-walls.json

Add Movie: The House with a Clock in Its Walls

---

actors/jason-statham.json

AddedActor_JasonStatham

---

directors/jon-turteltaub.json

AddedDirector_JonTurteltaub

---

actors/bingbing-li.json

AddedActor_BingbingLi

---

actors/rainn-wilson.json

AddedActor_RainnWilson

---

actors/sung-kang.json

Sung-Kang.json

---

actors/david-dobrik.json

David-dobrik.json

---

movies/1977/eraserhead.json

Eraserhead

---

movies/2018/annihilation.json

Add Annihilation

---

movies/2007/fool-and-final.json

added movie: Fool and Final 

---

movies/2004/50-first-dates.json

Add 50 First Dates

---

movies/1994/the-lion-king.json

feature: added The Lion King

---

movies/2018/bumblebee.json

Added Bumblebee

---

movies/2018/mortal-engines.json

Added mortal engines

---

movies/2018/johnny-english-strikes-again.json

Added Johnny English Strikes Again

---

movies/2018/vice.json

Added vice

---

movies/2018/ralph-breaks-the-internet.json

Added Wralph breaks the internet

---

movies/2018/overlord.json

Added overlord

---

movies/2018/goosebumps-2-haunted-halloween.json

Addition of Goosebumps 2: Haunted Halloween

---

movies/2018/tomb-raider.json

Tomb Radider 2018 Added

---

movies/2013/the-secret-life-of-walter-mitty.json

[Edited]: add the secret lift of walter mitty

---

directors/ang-lee.json
movies/2018/skyscraper.json

Add movie: Add skyscraper

---

movies/2001/jay-and-silent-bob-strike-back.json

Added in Jay and Silent Bob Strike Back

---

actors/ranjan-ramanayake.json

added a new srilankan actor ranjan ramanayake

---

actors/hasanga-lakdinu.json

add another superb actor

---

movies/2018/upgrade.json

Added upgrade

---

movies/1988/they-live.json

Add they-live.json

---

actors/rajinikanth.json
directors/karthik-subbaraj.json
movies/2018/petta.json

#687 add movie

---

actors/raffey-cassidy.json

Add actor name

---

movies/2018/solo-a-star-wars-story.json

adding solo: a star wars story

---

movies/2018/fifty-shades-freed.json

Adding movie Fifty Shades Freed

---

actors/rowan-atkinson.json

Create Actor Rowan Atkinson

---

directors/alfred-hitchcock.json
directors/zack-snyder.json
movies/2018/johnny-english-strikes-again.json

Zack Snyder added under directors

---

movies/1999/american-beauty.json

added american beauty movie

---

movies/2018/smallfoot.json

Add smallfoot

---

movies/2014/dukhtar.json

Add movie: Dukhtar, Fixes: #705

---

actors/daisuke-ono.json
actors/ikue-ootani.json
actors/kazuhiro-yamaji.json
actors/kenichi-ogata.json
actors/masaki-terasoma.json
actors/masako-katsuki.json
actors/megumi-hayashibara.json
actors/minami-takayama.json
actors/naoko-matsui.json
actors/norio-wakamoto.json
actors/rikiya-koyama.json
actors/ryo-horikawa.json
actors/ryotaro-okiayu.json
actors/satsuki-yukino.json
actors/wakana-yamazaki.json
actors/wataru-takagi.json
actors/yukiko-iwai.json
actors/yuko-miyamura.json
movies/2017/detective-conan-movie-21-karakurenai-no-love-letter.json

Add Detective Conan Movie 21 and actors

---

actors/suzu-hirose.json

Added new actor suzu hirose from Japan

Added actor - suzu hirose

---

movies/2016/your-lie-in-april.json

Added new entries for movie - your lie in april

Added movie - your lie in april

---

movies/2011/the-rite.json

The Rite (2011)

---

actors/jean-dujardin.json

Adding actor Jean Dujardin

---

movies/2015/kung-fury.json

add kung fury

---

actors/charlie-cox.json
actors/chloe-bennet.json

Added two actors, Charlie Cox and Chloe Bennet
I am here from Hacktoberfest

Added two more actors

---

actors/neve-campbell.json
directors/ang-lee.json
movies/2018/skyscraper.json

Add actor: Neve campbell

---

movies/2010/the-social-network.json

Added The Social Network to the movies folder

---

actors/kevin-hart.json

Add the actor Kevin Hart

---

actors/charlie-cox.json
actors/chloe-bennet.json

added a movie

---

actors/amitabh-bachchan.json

Added Amitabh Bachchan Actor

---

actors/johnny-depp.json
actors/zach-woods.json

Add actor: Johnny Depp, Zach Woods

---

movies/2018/bohemian-rhapsody.json

add Bohemian Rhapsody

---

movies/1974/la-patagonia-rebelde.json

#778 Add Movie: La Patagonia rebelde

---

actors/james-franco.json
actors/tommy-wiseau.json
movies/2017/kimi-no-na-wa-(your-name).json
movies/2017/the-disaster-artist.json

<Doesn't fix any issue>
Added a few movies which I didn't find in the collection

Added a few of my favorite movies and their actors

---

movies/2018/the-predator.json

added The Predator (2018)

---

movies/2018/hereditary.json

Add "Hereditary 2018"

---

movies/1994/dumb-and-dumber.json

Fixes: #810

---

movies/1992/death-becomes-her.json

Add death becomes her

---

movies/2016/allied.json

Create allied movie #816

---

directors/wes-anderson.json
movies/2018/isle-of-dogs.json

Added Wes Anderson as director and his 2018 movie 'Isle of Dogs'.

added-wes-anderson-and-isle-of-dogs

---

movies/1994/forrest-gump.json
movies/2014/dracula-untold.json

Added Movie Dracula Untold and Forrest Gump

---

directors/fritz-lang.json
directors/wes-anderson.json
movies/2018/isle-of-dogs.json

Added director Fritz Lang

---

movies/1987/spaceballs.json

Added Spaceballs (1987)

---

movies/1985/the-breakfast-club.json

Added Movie: The Breakfast Club (1985)

---

actors/adam-sandler.json

Added Adam Sandler

---

movies/1998/armageddon.json

added 1998 folder and armageddon movie

---

movies/2016/the-void.json

add the void

---

movies/2016/deadpool.json

add deadpool

---

movies/2016/jason-bourne.json

add Jason Bourne

---

movies/2003/finding-nemo.json

Add Finding Nemo (2003)

---

movies/1965/the-sound-of-music.json

Add Movie: The Sound of Music

---

movies/2018/hold-the-dark.json

Added Hold the Dark

---

movies/1991/the-silence-of-the-lambs.json
movies/2018/hold-the-dark.json

The silence of the lambs

---

movies/1996/independence-day.json

Add Movie: Independence Day #869

---

actors/doballah-reda.json

name added

---

movies/2013/coherence.json

Fixes #874 Added the movie Coherence (2013).

---

movies/2013/rush.json
readme.markdown

Added 'Sport' category and Rush movie

---

movies/2018/mission-impossible-fallout.json

Added Vanessa Kirby in MI-Fallout

---

actors/charlie-hunnam.json
actors/ron-perlman.json

Added Actor: Charlie Hunnam Fix #890 and Added Actor: Ron Perlman Fix #892
